### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by 7thCoder** [Tonysteve13/url-shortener#1]
After running npm install and then npm start i keep getting an error message
![npn](https://github.com/Tonysteve13/url-shortener/assets/101436061/8c063df8-e42a-4c8a-8fb3-508f792ba0d8)

**Comment by Tonysteve13** [comment]
Get to me on WhatsApp and show me how you running the code

**Comment by Tonysteve13** [comment]
Congratulations!
